In [29]:
import pandas as pd
import numpy as np

In [30]:
df= pd.read_csv('WELFake_Dataset.csv')

In [31]:
df.head()

Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1           1                                                NaN   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1     Did they post their votes for Hillary already?      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

In [32]:
df.isna().sum()

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [33]:
df= df.dropna()

In [34]:
df.isna().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [35]:
df.shape

(71537, 4)

In [36]:
df= df.reset_index()

In [37]:
df= df.drop(columns='Unnamed: 0')

In [38]:
df.head()

index                                              title  \
0      0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1      2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
2      3  Bobby Jindal, raised Hindu, uses story of Chri...   
3      4  SATAN 2: Russia unvelis an image of its terrif...   
4      5  About Time! Christian Group Sues Amazon and SP...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1   Now, most of the demonstrators gathered last ...      1  
2  A dozen politically active pastors came here f...      0  
3  The RS-28 Sarmat missile, dubbed Satan 2, will...      1  
4  All we can say on this one is it s about time ...      1

In [39]:
X= df.drop(columns='label', axis=1)
y= df['label']
X.shape

(71537, 3)

In [40]:
import tensorflow as tf

In [41]:
tf.__version__

'2.14.0'

In [26]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding

In [49]:
messages=X.copy()

In [50]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [51]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [55]:
corpus

['law enforc high alert follow threat cop white blacklivesmatt fyf terrorist video',
 'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video',
 'bobbi jindal rais hindu use stori christian convers woo evangel potenti bid',
 'satan russia unv imag terrifi new supernuk western world take notic',
 'time christian group sue amazon splc design hate group',
 'dr ben carson target ir never audit spoke nation prayer breakfast',
 'hous intel chair trump russia fake stori evid anyth video',
 'sport bar owner ban nfl game show true american sport like speak rural america video',
 'latest pipelin leak underscor danger dakota access pipelin',
 'gop senat smack punchabl alt right nazi internet',
 'may brexit offer would hurt cost eu citizen eu parliament',
 'schumer call trump appoint offici overse puerto rico relief',
 'watch hilari ad call question health age clinton crime famili boss',
 'chang expect espn polit agenda despit huge subscrib declin breitbart'

In [56]:
voc_size=10000
onehot_rep= [one_hot(words, voc_size)for words in corpus]

In [57]:
onehot_rep

[[3618, 4570, 9657, 390, 4542, 8568, 7398, 5551, 2820, 9529, 64, 2406],
 [4895,
  3837,
  573,
  6499,
  6828,
  5978,
  7683,
  1215,
  9286,
  3466,
  5279,
  3753,
  557,
  2406],
 [6997, 7807, 5298, 1708, 6322, 4996, 8281, 9623, 8936, 8170, 7822, 4999],
 [9390, 1773, 7058, 5662, 901, 7362, 6630, 3994, 3506, 8659, 463],
 [7512, 8281, 4924, 9972, 4527, 1595, 8266, 9930, 4924],
 [3140, 8072, 9652, 840, 8125, 9967, 2012, 7972, 9873, 134, 2451],
 [4050, 68, 9172, 8993, 1773, 2751, 4996, 8311, 8461, 2406],
 [8601,
  792,
  5243,
  4818,
  291,
  6539,
  5668,
  5577,
  7885,
  8601,
  2388,
  2807,
  7737,
  9729,
  2406],
 [5259, 4064, 1831, 3631, 1510, 8898, 7127, 4064],
 [1888, 7835, 8404, 963, 8376, 7204, 5683, 4154],
 [9753, 7255, 5733, 7716, 8055, 985, 1856, 329, 1856, 3261],
 [3674, 9360, 8993, 1748, 9242, 1050, 1884, 9355, 8409],
 [1843, 706, 6477, 9360, 60, 2877, 1674, 2813, 708, 2791, 8703],
 [7561, 9220, 5725, 6806, 8241, 4865, 2988, 537, 7973, 9719],
 [7153, 4043, 2287, 1474,

In [60]:
#Embedding layer- Post padding
sent_len=20
embeded= pad_sequences(onehot_rep,maxlen= sent_len, padding='post')
print (embeded)

[[3618 4570 9657 ...    0    0    0]
 [4895 3837  573 ...    0    0    0]
 [6997 7807 5298 ...    0    0    0]
 ...
 [ 730 7331 9521 ...    0    0    0]
 [8993 9692  944 ...    0    0    0]
 [4479 3476 3555 ...    0    0    0]]


In [86]:
#model creation
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length=sent_len))
model.add(LSTM(units=2, 100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss= 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

SyntaxError: positional argument follows keyword argument (979203848.py, line 5)

In [64]:
X_final=np.array(embeded)
y_final=np.array(y)

In [66]:
y_final.shape

(71537,)

In [67]:
from sklearn.model_selection import train_test_split

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.20, random_state=42)

In [73]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
895/895 [==============================] - 25s 25ms/step - loss: 0.3080 - accuracy: 0.8641 - val_loss: 0.2549 - val_accuracy: 0.8930
Epoch 2/10
895/895 [==============================] - 22s 25ms/step - loss: 0.2116 - accuracy: 0.9149 - val_loss: 0.2340 - val_accuracy: 0.9058
Epoch 3/10
895/895 [==============================] - 23s 26ms/step - loss: 0.1801 - accuracy: 0.9293 - val_loss: 0.2338 - val_accuracy: 0.9063
Epoch 4/10
895/895 [==============================] - 23s 25ms/step - loss: 0.1554 - accuracy: 0.9399 - val_loss: 0.2538 - val_accuracy: 0.9007
Epoch 5/10
895/895 [==============================] - 22s 25ms/step - loss: 0.1322 - accuracy: 0.9503 - val_loss: 0.2696 - val_accuracy: 0.9024
Epoch 6/10
895/895 [==============================] - 22s 25ms/step - loss: 0.1104 - accuracy: 0.9596 - val_loss: 0.2852 - val_accuracy: 0.9002
Epoch 7/10
895/895 [==============================] - 23s 25ms/step - loss: 0.0933 - accuracy: 0.9646 - val_loss: 0.2923 - val_accuracy:

In [76]:
y_pred= model.predict(X_test)

448/448 [==============================] - 2s 5ms/step


In [77]:
y_pred= np.where(y_pred>0.6,1,0)

In [78]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_pred, y_test))

[[6308  751]
 [ 773 6476]]


In [79]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89      7081
           1       0.89      0.90      0.89      7227

    accuracy                           0.89     14308
   macro avg       0.89      0.89      0.89     14308
weighted avg       0.89      0.89      0.89     14308



In [84]:
import pickle



In [85]:
pickle.dump(model, open('model.pkl','wb'))